--liquibase formatted sql

--changeset reviewbot:20250514-1
CREATE TABLE mr_slack_thread (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    gitlab_project_id BIGINT NOT NULL,
    mr_iid INTEGER NOT NULL,
    slack_channel_id VARCHAR(32) NOT NULL,
    root_message_ts VARCHAR(32) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_mr_slack_thread PRIMARY KEY (id),
    CONSTRAINT uk_mr_slack_thread_project_iid_channel UNIQUE (gitlab_project_id, mr_iid, slack_channel_id)
);
