--liquibase formatted sql

--changeset reviewbot:20250517-1
CREATE TABLE team_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    gitlab_project VARCHAR(512) NOT NULL,
    slack_channel_id VARCHAR(32) NOT NULL,
    CONSTRAINT pk_team_rule PRIMARY KEY (id),
    CONSTRAINT uk_team_rule_project_channel UNIQUE (gitlab_project, slack_channel_id)
);

CREATE INDEX idx_team_rule_gitlab_project ON team_rule (gitlab_project);
